/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 uploads_files_3630650_city.glb 
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function City(props) {
//   const { nodes, materials } = useGLTF('/city.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group position={[-3.904, 0.742, 3.873]} rotation={[0, -1.251, 1.571]} scale={0.022}>
//         <mesh geometry={nodes['BuildingMesh-00237_1'].geometry} material={materials['BuildingMat-00237']} />
//         <mesh geometry={nodes['BuildingMesh-00237_2'].geometry} material={materials['BuildingMat-00000']} />
//         <mesh geometry={nodes['BuildingMesh-00237_3'].geometry} material={materials['BuildingMat-00001']} />
//         <mesh geometry={nodes['BuildingMesh-00237_4'].geometry} material={materials['BuildingMat-00002']} />
//         <mesh geometry={nodes['BuildingMesh-00237_5'].geometry} material={materials['BuildingMat-00003']} />
//         <mesh geometry={nodes['BuildingMesh-00237_6'].geometry} material={materials['BuildingMat-00004']} />
//         <mesh geometry={nodes['BuildingMesh-00237_7'].geometry} material={materials['BuildingMat-00005']} />
//         <mesh geometry={nodes['BuildingMesh-00237_8'].geometry} material={materials['BuildingMat-00006']} />
//         <mesh geometry={nodes['BuildingMesh-00237_9'].geometry} material={materials['BuildingMat-00007']} />
//         <mesh geometry={nodes['BuildingMesh-00237_10'].geometry} material={materials['BuildingMat-00008']} />
//         <mesh geometry={nodes['BuildingMesh-00237_11'].geometry} material={materials['BuildingMat-00009']} />
//         <mesh geometry={nodes['BuildingMesh-00237_12'].geometry} material={materials['BuildingMat-00010']} />
//         <mesh geometry={nodes['BuildingMesh-00237_13'].geometry} material={materials['BuildingMat-00011']} />
//         <mesh geometry={nodes['BuildingMesh-00237_14'].geometry} material={materials['BuildingMat-00012']} />
//         <mesh geometry={nodes['BuildingMesh-00237_15'].geometry} material={materials['BuildingMat-00013']} />
//         <mesh geometry={nodes['BuildingMesh-00237_16'].geometry} material={materials['BuildingMat-00014']} />
//         <mesh geometry={nodes['BuildingMesh-00237_17'].geometry} material={materials['BuildingMat-00015']} />
//         <mesh geometry={nodes['BuildingMesh-00237_18'].geometry} material={materials['BuildingMat-00016']} />
//         <mesh geometry={nodes['BuildingMesh-00237_19'].geometry} material={materials['BuildingMat-00017']} />
//         <mesh geometry={nodes['BuildingMesh-00237_20'].geometry} material={materials['BuildingMat-00018']} />
//         <mesh geometry={nodes['BuildingMesh-00237_21'].geometry} material={materials['BuildingMat-00019']} />
//         <mesh geometry={nodes['BuildingMesh-00237_22'].geometry} material={materials['BuildingMat-00020']} />
//         <mesh geometry={nodes['BuildingMesh-00237_23'].geometry} material={materials['BuildingMat-00021']} />
//         <mesh geometry={nodes['BuildingMesh-00237_24'].geometry} material={materials['BuildingMat-00022']} />
//         <mesh geometry={nodes['BuildingMesh-00237_25'].geometry} material={materials['BuildingMat-00023']} />
//         <mesh geometry={nodes['BuildingMesh-00237_26'].geometry} material={materials['BuildingMat-00024']} />
//         <mesh geometry={nodes['BuildingMesh-00237_27'].geometry} material={materials['BuildingMat-00025']} />
//         <mesh geometry={nodes['BuildingMesh-00237_28'].geometry} material={materials['BuildingMat-00026']} />
//         <mesh geometry={nodes['BuildingMesh-00237_29'].geometry} material={materials['BuildingMat-00027']} />
//         <mesh geometry={nodes['BuildingMesh-00237_30'].geometry} material={materials['BuildingMat-00028']} />
//         <mesh geometry={nodes['BuildingMesh-00237_31'].geometry} material={materials['BuildingMat-00029']} />
//         <mesh geometry={nodes['BuildingMesh-00237_32'].geometry} material={materials['BuildingMat-00030']} />
//         <mesh geometry={nodes['BuildingMesh-00237_33'].geometry} material={materials['BuildingMat-00031']} />
//         <mesh geometry={nodes['BuildingMesh-00237_34'].geometry} material={materials['BuildingMat-00032']} />
//         <mesh geometry={nodes['BuildingMesh-00237_35'].geometry} material={materials['BuildingMat-00033']} />
//         <mesh geometry={nodes['BuildingMesh-00237_36'].geometry} material={materials['BuildingMat-00034']} />
//         <mesh geometry={nodes['BuildingMesh-00237_37'].geometry} material={materials['BuildingMat-00035']} />
//         <mesh geometry={nodes['BuildingMesh-00237_38'].geometry} material={materials['BuildingMat-00036']} />
//         <mesh geometry={nodes['BuildingMesh-00237_39'].geometry} material={materials['BuildingMat-00037']} />
//         <mesh geometry={nodes['BuildingMesh-00237_40'].geometry} material={materials['BuildingMat-00038']} />
//         <mesh geometry={nodes['BuildingMesh-00237_41'].geometry} material={materials['BuildingMat-00039']} />
//         <mesh geometry={nodes['BuildingMesh-00237_42'].geometry} material={materials['BuildingMat-00040']} />
//         <mesh geometry={nodes['BuildingMesh-00237_43'].geometry} material={materials['BuildingMat-00041']} />
//         <mesh geometry={nodes['BuildingMesh-00237_44'].geometry} material={materials['BuildingMat-00042']} />
//         <mesh geometry={nodes['BuildingMesh-00237_45'].geometry} material={materials['BuildingMat-00043']} />
//         <mesh geometry={nodes['BuildingMesh-00237_46'].geometry} material={materials['BuildingMat-00044']} />
//         <mesh geometry={nodes['BuildingMesh-00237_47'].geometry} material={materials['BuildingMat-00045']} />
//         <mesh geometry={nodes['BuildingMesh-00237_48'].geometry} material={materials['BuildingMat-00046']} />
//         <mesh geometry={nodes['BuildingMesh-00237_49'].geometry} material={materials['BuildingMat-00047']} />
//         <mesh geometry={nodes['BuildingMesh-00237_50'].geometry} material={materials['BuildingMat-00048']} />
//         <mesh geometry={nodes['BuildingMesh-00237_51'].geometry} material={materials['BuildingMat-00049']} />
//         <mesh geometry={nodes['BuildingMesh-00237_52'].geometry} material={materials['BuildingMat-00050']} />
//         <mesh geometry={nodes['BuildingMesh-00237_53'].geometry} material={materials['BuildingMat-00051']} />
//         <mesh geometry={nodes['BuildingMesh-00237_54'].geometry} material={materials['BuildingMat-00052']} />
//         <mesh geometry={nodes['BuildingMesh-00237_55'].geometry} material={materials['BuildingMat-00053']} />
//         <mesh geometry={nodes['BuildingMesh-00237_56'].geometry} material={materials['BuildingMat-00054']} />
//         <mesh geometry={nodes['BuildingMesh-00237_57'].geometry} material={materials['BuildingMat-00055']} />
//         <mesh geometry={nodes['BuildingMesh-00237_58'].geometry} material={materials['BuildingMat-00056']} />
//         <mesh geometry={nodes['BuildingMesh-00237_59'].geometry} material={materials['BuildingMat-00057']} />
//         <mesh geometry={nodes['BuildingMesh-00237_60'].geometry} material={materials['BuildingMat-00058']} />
//         <mesh geometry={nodes['BuildingMesh-00237_61'].geometry} material={materials['BuildingMat-00059']} />
//         <mesh geometry={nodes['BuildingMesh-00237_62'].geometry} material={materials['BuildingMat-00060']} />
//         <mesh geometry={nodes['BuildingMesh-00237_63'].geometry} material={materials['BuildingMat-00061']} />
//         <mesh geometry={nodes['BuildingMesh-00237_64'].geometry} material={materials['BuildingMat-00062']} />
//         <mesh geometry={nodes['BuildingMesh-00237_65'].geometry} material={materials['BuildingMat-00063']} />
//         <mesh geometry={nodes['BuildingMesh-00237_66'].geometry} material={materials['BuildingMat-00064']} />
//         <mesh geometry={nodes['BuildingMesh-00237_67'].geometry} material={materials['BuildingMat-00065']} />
//         <mesh geometry={nodes['BuildingMesh-00237_68'].geometry} material={materials['BuildingMat-00066']} />
//         <mesh geometry={nodes['BuildingMesh-00237_69'].geometry} material={materials['BuildingMat-00067']} />
//         <mesh geometry={nodes['BuildingMesh-00237_70'].geometry} material={materials['BuildingMat-00068']} />
//         <mesh geometry={nodes['BuildingMesh-00237_71'].geometry} material={materials['BuildingMat-00069']} />
//         <mesh geometry={nodes['BuildingMesh-00237_72'].geometry} material={materials['BuildingMat-00070']} />
//         <mesh geometry={nodes['BuildingMesh-00237_73'].geometry} material={materials['BuildingMat-00071']} />
//         <mesh geometry={nodes['BuildingMesh-00237_74'].geometry} material={materials['BuildingMat-00072']} />
//         <mesh geometry={nodes['BuildingMesh-00237_75'].geometry} material={materials['BuildingMat-00073']} />
//         <mesh geometry={nodes['BuildingMesh-00237_76'].geometry} material={materials['BuildingMat-00074']} />
//         <mesh geometry={nodes['BuildingMesh-00237_77'].geometry} material={materials['BuildingMat-00075']} />
//         <mesh geometry={nodes['BuildingMesh-00237_78'].geometry} material={materials['BuildingMat-00076']} />
//         <mesh geometry={nodes['BuildingMesh-00237_79'].geometry} material={materials['BuildingMat-00077']} />
//         <mesh geometry={nodes['BuildingMesh-00237_80'].geometry} material={materials['BuildingMat-00078']} />
//         <mesh geometry={nodes['BuildingMesh-00237_81'].geometry} material={materials['BuildingMat-00079']} />
//         <mesh geometry={nodes['BuildingMesh-00237_82'].geometry} material={materials['BuildingMat-00080']} />
//         <mesh geometry={nodes['BuildingMesh-00237_83'].geometry} material={materials['BuildingMat-00081']} />
//         <mesh geometry={nodes['BuildingMesh-00237_84'].geometry} material={materials['BuildingMat-00082']} />
//         <mesh geometry={nodes['BuildingMesh-00237_85'].geometry} material={materials['BuildingMat-00083']} />
//         <mesh geometry={nodes['BuildingMesh-00237_86'].geometry} material={materials['BuildingMat-00084']} />
//         <mesh geometry={nodes['BuildingMesh-00237_87'].geometry} material={materials['BuildingMat-00085']} />
//         <mesh geometry={nodes['BuildingMesh-00237_88'].geometry} material={materials['BuildingMat-00086']} />
//         <mesh geometry={nodes['BuildingMesh-00237_89'].geometry} material={materials['BuildingMat-00087']} />
//         <mesh geometry={nodes['BuildingMesh-00237_90'].geometry} material={materials['BuildingMat-00088']} />
//         <mesh geometry={nodes['BuildingMesh-00237_91'].geometry} material={materials['BuildingMat-00089']} />
//         <mesh geometry={nodes['BuildingMesh-00237_92'].geometry} material={materials['BuildingMat-00090']} />
//         <mesh geometry={nodes['BuildingMesh-00237_93'].geometry} material={materials['BuildingMat-00091']} />
//         <mesh geometry={nodes['BuildingMesh-00237_94'].geometry} material={materials['BuildingMat-00092']} />
//         <mesh geometry={nodes['BuildingMesh-00237_95'].geometry} material={materials['BuildingMat-00093']} />
//         <mesh geometry={nodes['BuildingMesh-00237_96'].geometry} material={materials['BuildingMat-00094']} />
//         <mesh geometry={nodes['BuildingMesh-00237_97'].geometry} material={materials['BuildingMat-00095']} />
//         <mesh geometry={nodes['BuildingMesh-00237_98'].geometry} material={materials['BuildingMat-00096']} />
//         <mesh geometry={nodes['BuildingMesh-00237_99'].geometry} material={materials['BuildingMat-00097']} />
//         <mesh geometry={nodes['BuildingMesh-00237_100'].geometry} material={materials['BuildingMat-00098']} />
//         <mesh geometry={nodes['BuildingMesh-00237_101'].geometry} material={materials['BuildingMat-00099']} />
//         <mesh geometry={nodes['BuildingMesh-00237_102'].geometry} material={materials['BuildingMat-00100']} />
//         <mesh geometry={nodes['BuildingMesh-00237_103'].geometry} material={materials['BuildingMat-00101']} />
//         <mesh geometry={nodes['BuildingMesh-00237_104'].geometry} material={materials['BuildingMat-00102']} />
//         <mesh geometry={nodes['BuildingMesh-00237_105'].geometry} material={materials['BuildingMat-00103']} />
//         <mesh geometry={nodes['BuildingMesh-00237_106'].geometry} material={materials['BuildingMat-00104']} />
//         <mesh geometry={nodes['BuildingMesh-00237_107'].geometry} material={materials['BuildingMat-00105']} />
//         <mesh geometry={nodes['BuildingMesh-00237_108'].geometry} material={materials['BuildingMat-00106']} />
//         <mesh geometry={nodes['BuildingMesh-00237_109'].geometry} material={materials['BuildingMat-00107']} />
//         <mesh geometry={nodes['BuildingMesh-00237_110'].geometry} material={materials['BuildingMat-00108']} />
//         <mesh geometry={nodes['BuildingMesh-00237_111'].geometry} material={materials['BuildingMat-00109']} />
//         <mesh geometry={nodes['BuildingMesh-00237_112'].geometry} material={materials['BuildingMat-00110']} />
//         <mesh geometry={nodes['BuildingMesh-00237_113'].geometry} material={materials['BuildingMat-00111']} />
//         <mesh geometry={nodes['BuildingMesh-00237_114'].geometry} material={materials['BuildingMat-00112']} />
//         <mesh geometry={nodes['BuildingMesh-00237_115'].geometry} material={materials['BuildingMat-00113']} />
//         <mesh geometry={nodes['BuildingMesh-00237_116'].geometry} material={materials['BuildingMat-00114']} />
//         <mesh geometry={nodes['BuildingMesh-00237_117'].geometry} material={materials['BuildingMat-00115']} />
//         <mesh geometry={nodes['BuildingMesh-00237_118'].geometry} material={materials['BuildingMat-00116']} />
//         <mesh geometry={nodes['BuildingMesh-00237_119'].geometry} material={materials['BuildingMat-00117']} />
//         <mesh geometry={nodes['BuildingMesh-00237_120'].geometry} material={materials['BuildingMat-00118']} />
//         <mesh geometry={nodes['BuildingMesh-00237_121'].geometry} material={materials['BuildingMat-00119']} />
//         <mesh geometry={nodes['BuildingMesh-00237_122'].geometry} material={materials['BuildingMat-00120']} />
//         <mesh geometry={nodes['BuildingMesh-00237_123'].geometry} material={materials['BuildingMat-00121']} />
//         <mesh geometry={nodes['BuildingMesh-00237_124'].geometry} material={materials['BuildingMat-00122']} />
//         <mesh geometry={nodes['BuildingMesh-00237_125'].geometry} material={materials['BuildingMat-00123']} />
//         <mesh geometry={nodes['BuildingMesh-00237_126'].geometry} material={materials['BuildingMat-00124']} />
//         <mesh geometry={nodes['BuildingMesh-00237_127'].geometry} material={materials['BuildingMat-00125']} />
//         <mesh geometry={nodes['BuildingMesh-00237_128'].geometry} material={materials['BuildingMat-00126']} />
//         <mesh geometry={nodes['BuildingMesh-00237_129'].geometry} material={materials['BuildingMat-00127']} />
//         <mesh geometry={nodes['BuildingMesh-00237_130'].geometry} material={materials['BuildingMat-00128']} />
//         <mesh geometry={nodes['BuildingMesh-00237_131'].geometry} material={materials['BuildingMat-00129']} />
//         <mesh geometry={nodes['BuildingMesh-00237_132'].geometry} material={materials['BuildingMat-00130']} />
//         <mesh geometry={nodes['BuildingMesh-00237_133'].geometry} material={materials['BuildingMat-00131']} />
//         <mesh geometry={nodes['BuildingMesh-00237_134'].geometry} material={materials['BuildingMat-00132']} />
//         <mesh geometry={nodes['BuildingMesh-00237_135'].geometry} material={materials['BuildingMat-00133']} />
//         <mesh geometry={nodes['BuildingMesh-00237_136'].geometry} material={materials['BuildingMat-00134']} />
//         <mesh geometry={nodes['BuildingMesh-00237_137'].geometry} material={materials['BuildingMat-00135']} />
//         <mesh geometry={nodes['BuildingMesh-00237_138'].geometry} material={materials['BuildingMat-00136']} />
//         <mesh geometry={nodes['BuildingMesh-00237_139'].geometry} material={materials['BuildingMat-00137']} />
//         <mesh geometry={nodes['BuildingMesh-00237_140'].geometry} material={materials['BuildingMat-00138']} />
//         <mesh geometry={nodes['BuildingMesh-00237_141'].geometry} material={materials['BuildingMat-00139']} />
//         <mesh geometry={nodes['BuildingMesh-00237_142'].geometry} material={materials['BuildingMat-00140']} />
//         <mesh geometry={nodes['BuildingMesh-00237_143'].geometry} material={materials['BuildingMat-00141']} />
//         <mesh geometry={nodes['BuildingMesh-00237_144'].geometry} material={materials['BuildingMat-00142']} />
//         <mesh geometry={nodes['BuildingMesh-00237_145'].geometry} material={materials['BuildingMat-00143']} />
//         <mesh geometry={nodes['BuildingMesh-00237_146'].geometry} material={materials['BuildingMat-00144']} />
//         <mesh geometry={nodes['BuildingMesh-00237_147'].geometry} material={materials['BuildingMat-00145']} />
//         <mesh geometry={nodes['BuildingMesh-00237_148'].geometry} material={materials['BuildingMat-00146']} />
//         <mesh geometry={nodes['BuildingMesh-00237_149'].geometry} material={materials['BuildingMat-00147']} />
//         <mesh geometry={nodes['BuildingMesh-00237_150'].geometry} material={materials['BuildingMat-00148']} />
//         <mesh geometry={nodes['BuildingMesh-00237_151'].geometry} material={materials['BuildingMat-00149']} />
//         <mesh geometry={nodes['BuildingMesh-00237_152'].geometry} material={materials['BuildingMat-00150']} />
//         <mesh geometry={nodes['BuildingMesh-00237_153'].geometry} material={materials['BuildingMat-00151']} />
//         <mesh geometry={nodes['BuildingMesh-00237_154'].geometry} material={materials['BuildingMat-00152']} />
//         <mesh geometry={nodes['BuildingMesh-00237_155'].geometry} material={materials['BuildingMat-00153']} />
//         <mesh geometry={nodes['BuildingMesh-00237_156'].geometry} material={materials['BuildingMat-00154']} />
//         <mesh geometry={nodes['BuildingMesh-00237_157'].geometry} material={materials['BuildingMat-00155']} />
//         <mesh geometry={nodes['BuildingMesh-00237_158'].geometry} material={materials['BuildingMat-00156']} />
//         <mesh geometry={nodes['BuildingMesh-00237_159'].geometry} material={materials['BuildingMat-00157']} />
//         <mesh geometry={nodes['BuildingMesh-00237_160'].geometry} material={materials['BuildingMat-00158']} />
//         <mesh geometry={nodes['BuildingMesh-00237_161'].geometry} material={materials['BuildingMat-00159']} />
//         <mesh geometry={nodes['BuildingMesh-00237_162'].geometry} material={materials['BuildingMat-00160']} />
//         <mesh geometry={nodes['BuildingMesh-00237_163'].geometry} material={materials['BuildingMat-00161']} />
//         <mesh geometry={nodes['BuildingMesh-00237_164'].geometry} material={materials['BuildingMat-00162']} />
//         <mesh geometry={nodes['BuildingMesh-00237_165'].geometry} material={materials['BuildingMat-00163']} />
//         <mesh geometry={nodes['BuildingMesh-00237_166'].geometry} material={materials['BuildingMat-00164']} />
//         <mesh geometry={nodes['BuildingMesh-00237_167'].geometry} material={materials['BuildingMat-00165']} />
//         <mesh geometry={nodes['BuildingMesh-00237_168'].geometry} material={materials['BuildingMat-00166']} />
//         <mesh geometry={nodes['BuildingMesh-00237_169'].geometry} material={materials['BuildingMat-00167']} />
//         <mesh geometry={nodes['BuildingMesh-00237_170'].geometry} material={materials['BuildingMat-00168']} />
//         <mesh geometry={nodes['BuildingMesh-00237_171'].geometry} material={materials['BuildingMat-00169']} />
//         <mesh geometry={nodes['BuildingMesh-00237_172'].geometry} material={materials['BuildingMat-00170']} />
//         <mesh geometry={nodes['BuildingMesh-00237_173'].geometry} material={materials['BuildingMat-00171']} />
//         <mesh geometry={nodes['BuildingMesh-00237_174'].geometry} material={materials['BuildingMat-00172']} />
//         <mesh geometry={nodes['BuildingMesh-00237_175'].geometry} material={materials['BuildingMat-00173']} />
//         <mesh geometry={nodes['BuildingMesh-00237_176'].geometry} material={materials['BuildingMat-00174']} />
//         <mesh geometry={nodes['BuildingMesh-00237_177'].geometry} material={materials['BuildingMat-00175']} />
//         <mesh geometry={nodes['BuildingMesh-00237_178'].geometry} material={materials['BuildingMat-00176']} />
//         <mesh geometry={nodes['BuildingMesh-00237_179'].geometry} material={materials['BuildingMat-00177']} />
//         <mesh geometry={nodes['BuildingMesh-00237_180'].geometry} material={materials['BuildingMat-00178']} />
//         <mesh geometry={nodes['BuildingMesh-00237_181'].geometry} material={materials['BuildingMat-00179']} />
//         <mesh geometry={nodes['BuildingMesh-00237_182'].geometry} material={materials['BuildingMat-00180']} />
//         <mesh geometry={nodes['BuildingMesh-00237_183'].geometry} material={materials['BuildingMat-00181']} />
//         <mesh geometry={nodes['BuildingMesh-00237_184'].geometry} material={materials['BuildingMat-00182']} />
//         <mesh geometry={nodes['BuildingMesh-00237_185'].geometry} material={materials['BuildingMat-00183']} />
//         <mesh geometry={nodes['BuildingMesh-00237_186'].geometry} material={materials['BuildingMat-00184']} />
//         <mesh geometry={nodes['BuildingMesh-00237_187'].geometry} material={materials['BuildingMat-00185']} />
//         <mesh geometry={nodes['BuildingMesh-00237_188'].geometry} material={materials['BuildingMat-00186']} />
//         <mesh geometry={nodes['BuildingMesh-00237_189'].geometry} material={materials['BuildingMat-00187']} />
//         <mesh geometry={nodes['BuildingMesh-00237_190'].geometry} material={materials['BuildingMat-00188']} />
//         <mesh geometry={nodes['BuildingMesh-00237_191'].geometry} material={materials['BuildingMat-00189']} />
//         <mesh geometry={nodes['BuildingMesh-00237_192'].geometry} material={materials['BuildingMat-00190']} />
//         <mesh geometry={nodes['BuildingMesh-00237_193'].geometry} material={materials['BuildingMat-00191']} />
//         <mesh geometry={nodes['BuildingMesh-00237_194'].geometry} material={materials['BuildingMat-00192']} />
//         <mesh geometry={nodes['BuildingMesh-00237_195'].geometry} material={materials['BuildingMat-00193']} />
//         <mesh geometry={nodes['BuildingMesh-00237_196'].geometry} material={materials['BuildingMat-00194']} />
//         <mesh geometry={nodes['BuildingMesh-00237_197'].geometry} material={materials['BuildingMat-00195']} />
//         <mesh geometry={nodes['BuildingMesh-00237_198'].geometry} material={materials['BuildingMat-00196']} />
//         <mesh geometry={nodes['BuildingMesh-00237_199'].geometry} material={materials['BuildingMat-00197']} />
//         <mesh geometry={nodes['BuildingMesh-00237_200'].geometry} material={materials['BuildingMat-00198']} />
//         <mesh geometry={nodes['BuildingMesh-00237_201'].geometry} material={materials['BuildingMat-00199']} />
//         <mesh geometry={nodes['BuildingMesh-00237_202'].geometry} material={materials['BuildingMat-00200']} />
//         <mesh geometry={nodes['BuildingMesh-00237_203'].geometry} material={materials['BuildingMat-00201']} />
//         <mesh geometry={nodes['BuildingMesh-00237_204'].geometry} material={materials['BuildingMat-00202']} />
//         <mesh geometry={nodes['BuildingMesh-00237_205'].geometry} material={materials['BuildingMat-00203']} />
//         <mesh geometry={nodes['BuildingMesh-00237_206'].geometry} material={materials['BuildingMat-00204']} />
//         <mesh geometry={nodes['BuildingMesh-00237_207'].geometry} material={materials['BuildingMat-00205']} />
//         <mesh geometry={nodes['BuildingMesh-00237_208'].geometry} material={materials['BuildingMat-00206']} />
//         <mesh geometry={nodes['BuildingMesh-00237_209'].geometry} material={materials['BuildingMat-00207']} />
//         <mesh geometry={nodes['BuildingMesh-00237_210'].geometry} material={materials['BuildingMat-00208']} />
//         <mesh geometry={nodes['BuildingMesh-00237_211'].geometry} material={materials['BuildingMat-00209']} />
//         <mesh geometry={nodes['BuildingMesh-00237_212'].geometry} material={materials['BuildingMat-00210']} />
//         <mesh geometry={nodes['BuildingMesh-00237_213'].geometry} material={materials['BuildingMat-00211']} />
//         <mesh geometry={nodes['BuildingMesh-00237_214'].geometry} material={materials['BuildingMat-00212']} />
//         <mesh geometry={nodes['BuildingMesh-00237_215'].geometry} material={materials['BuildingMat-00213']} />
//         <mesh geometry={nodes['BuildingMesh-00237_216'].geometry} material={materials['BuildingMat-00214']} />
//         <mesh geometry={nodes['BuildingMesh-00237_217'].geometry} material={materials['BuildingMat-00215']} />
//         <mesh geometry={nodes['BuildingMesh-00237_218'].geometry} material={materials['BuildingMat-00216']} />
//         <mesh geometry={nodes['BuildingMesh-00237_219'].geometry} material={materials['BuildingMat-00217']} />
//         <mesh geometry={nodes['BuildingMesh-00237_220'].geometry} material={materials['BuildingMat-00218']} />
//         <mesh geometry={nodes['BuildingMesh-00237_221'].geometry} material={materials['BuildingMat-00219']} />
//         <mesh geometry={nodes['BuildingMesh-00237_222'].geometry} material={materials['BuildingMat-00220']} />
//         <mesh geometry={nodes['BuildingMesh-00237_223'].geometry} material={materials['BuildingMat-00221']} />
//         <mesh geometry={nodes['BuildingMesh-00237_224'].geometry} material={materials['BuildingMat-00222']} />
//         <mesh geometry={nodes['BuildingMesh-00237_225'].geometry} material={materials['BuildingMat-00223']} />
//         <mesh geometry={nodes['BuildingMesh-00237_226'].geometry} material={materials['BuildingMat-00224']} />
//         <mesh geometry={nodes['BuildingMesh-00237_227'].geometry} material={materials['BuildingMat-00225']} />
//         <mesh geometry={nodes['BuildingMesh-00237_228'].geometry} material={materials['BuildingMat-00226']} />
//         <mesh geometry={nodes['BuildingMesh-00237_229'].geometry} material={materials['BuildingMat-00227']} />
//         <mesh geometry={nodes['BuildingMesh-00237_230'].geometry} material={materials['BuildingMat-00228']} />
//         <mesh geometry={nodes['BuildingMesh-00237_231'].geometry} material={materials['BuildingMat-00229']} />
//         <mesh geometry={nodes['BuildingMesh-00237_232'].geometry} material={materials['BuildingMat-00230']} />
//         <mesh geometry={nodes['BuildingMesh-00237_233'].geometry} material={materials['BuildingMat-00231']} />
//         <mesh geometry={nodes['BuildingMesh-00237_234'].geometry} material={materials['BuildingMat-00232']} />
//         <mesh geometry={nodes['BuildingMesh-00237_235'].geometry} material={materials['BuildingMat-00233']} />
//         <mesh geometry={nodes['BuildingMesh-00237_236'].geometry} material={materials['BuildingMat-00234']} />
//         <mesh geometry={nodes['BuildingMesh-00237_237'].geometry} material={materials['BuildingMat-00235']} />
//         <mesh geometry={nodes['BuildingMesh-00237_238'].geometry} material={materials['BuildingMat-00236']} />
//         <mesh geometry={nodes['BuildingMesh-00237_239'].geometry} material={materials['BuildingMat-00238']} />
//         <mesh geometry={nodes['BuildingMesh-00237_240'].geometry} material={materials['BuildingMat-00239']} />
//         <mesh geometry={nodes['BuildingMesh-00237_241'].geometry} material={materials['BuildingMat-00240']} />
//         <mesh geometry={nodes['BuildingMesh-00237_242'].geometry} material={materials['BuildingMat-00241']} />
//         <mesh geometry={nodes['BuildingMesh-00237_243'].geometry} material={materials['BuildingMat-00242']} />
//         <mesh geometry={nodes['BuildingMesh-00237_244'].geometry} material={materials['BuildingMat-00243']} />
//         <mesh geometry={nodes['BuildingMesh-00237_245'].geometry} material={materials['BuildingMat-00244']} />
//         <mesh geometry={nodes['BuildingMesh-00237_246'].geometry} material={materials['BuildingMat-00245']} />
//         <mesh geometry={nodes['BuildingMesh-00237_247'].geometry} material={materials['BuildingMat-00246']} />
//         <mesh geometry={nodes['BuildingMesh-00237_248'].geometry} material={materials['BuildingMat-00247']} />
//         <mesh geometry={nodes['BuildingMesh-00237_249'].geometry} material={materials['BuildingMat-00248']} />
//         <mesh geometry={nodes['BuildingMesh-00237_250'].geometry} material={materials['BuildingMat-00249']} />
//         <mesh geometry={nodes['BuildingMesh-00237_251'].geometry} material={materials['BuildingMat-00250']} />
//         <mesh geometry={nodes['BuildingMesh-00237_252'].geometry} material={materials['BuildingMat-00251']} />
//         <mesh geometry={nodes['BuildingMesh-00237_253'].geometry} material={materials['BuildingMat-00252']} />
//         <mesh geometry={nodes['BuildingMesh-00237_254'].geometry} material={materials['BuildingMat-00253']} />
//         <mesh geometry={nodes['BuildingMesh-00237_255'].geometry} material={materials['BuildingMat-00254']} />
//         <mesh geometry={nodes['BuildingMesh-00237_256'].geometry} material={materials['BuildingMat-00255']} />
//         <mesh geometry={nodes['BuildingMesh-00237_257'].geometry} material={materials['BuildingMat-00256']} />
//         <mesh geometry={nodes['BuildingMesh-00237_258'].geometry} material={materials['BuildingMat-00257']} />
//         <mesh geometry={nodes['BuildingMesh-00237_259'].geometry} material={materials['BuildingMat-00258']} />
//         <mesh geometry={nodes['BuildingMesh-00237_260'].geometry} material={materials['BuildingMat-00259']} />
//         <mesh geometry={nodes['BuildingMesh-00237_261'].geometry} material={materials['BuildingMat-00260']} />
//         <mesh geometry={nodes['BuildingMesh-00237_262'].geometry} material={materials['BuildingMat-00261']} />
//         <mesh geometry={nodes['BuildingMesh-00237_263'].geometry} material={materials['BuildingMat-00262']} />
//         <mesh geometry={nodes['BuildingMesh-00237_264'].geometry} material={materials['BuildingMat-00263']} />
//         <mesh geometry={nodes['BuildingMesh-00237_265'].geometry} material={materials['BuildingMat-00264']} />
//         <mesh geometry={nodes['BuildingMesh-00237_266'].geometry} material={materials['BuildingMat-00265']} />
//         <mesh geometry={nodes['BuildingMesh-00237_267'].geometry} material={materials['BuildingMat-00266']} />
//         <mesh geometry={nodes['BuildingMesh-00237_268'].geometry} material={materials['BuildingMat-00267']} />
//         <mesh geometry={nodes['BuildingMesh-00237_269'].geometry} material={materials['BuildingMat-00268']} />
//         <mesh geometry={nodes['BuildingMesh-00237_270'].geometry} material={materials['BuildingMat-00269']} />
//         <mesh geometry={nodes['BuildingMesh-00237_271'].geometry} material={materials['BuildingMat-00270']} />
//         <mesh geometry={nodes['BuildingMesh-00237_272'].geometry} material={materials['BuildingMat-00271']} />
//         <mesh geometry={nodes['BuildingMesh-00237_273'].geometry} material={materials['BuildingMat-00272']} />
//         <mesh geometry={nodes['BuildingMesh-00237_274'].geometry} material={materials['BuildingMat-00273']} />
//         <mesh geometry={nodes['BuildingMesh-00237_275'].geometry} material={materials['BuildingMat-00274']} />
//         <mesh geometry={nodes['BuildingMesh-00237_276'].geometry} material={materials['BuildingMat-00275']} />
//         <mesh geometry={nodes['BuildingMesh-00237_277'].geometry} material={materials['BuildingMat-00276']} />
//         <mesh geometry={nodes['BuildingMesh-00237_278'].geometry} material={materials['BuildingMat-00277']} />
//         <mesh geometry={nodes['BuildingMesh-00237_279'].geometry} material={materials['BuildingMat-00278']} />
//         <mesh geometry={nodes['BuildingMesh-00237_280'].geometry} material={materials['BuildingMat-00279']} />
//         <mesh geometry={nodes['BuildingMesh-00237_281'].geometry} material={materials['BuildingMat-00281']} />
//         <mesh geometry={nodes['BuildingMesh-00237_282'].geometry} material={materials['BuildingMat-00282']} />
//         <mesh geometry={nodes['BuildingMesh-00237_283'].geometry} material={materials['BuildingMat-00283']} />
//         <mesh geometry={nodes['BuildingMesh-00237_284'].geometry} material={materials['BuildingMat-00284']} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/uploads_files_3630650_city.glb')

import React, { useState, useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function City({
  zoom = 1,
  rotationSpeed = 0.005,
  isHeatmapVisible,
  heatmapData,
  heatmapMaterial,
  ...props
}) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/city.glb");
  const { actions } = useAnimations(animations, group);
  const [originalMaterials, setOriginalMaterials] = useState({});
  const [heatMapVisible, setHeatMapVisible] = useState(false);

  useEffect(() => {
    const originalMaterialsObj = {};
    Object.values(materials).forEach((material) => {
      originalMaterialsObj[material.name] = material;
      console.log(material);
    });
    setOriginalMaterials(originalMaterialsObj);
  }, []);

  useEffect(() => {
    group.current.scale.set(zoom, zoom, zoom);

    // Store original materials by name when component mounts
    // const originalMaterialsObj = {};
    // Object.values(materials).forEach(material => {
    //   originalMaterialsObj[material.name] = material;
    // });
    // setOriginalMaterials(originalMaterialsObj);
  }, [zoom, materials, isHeatmapVisible]);

  useEffect(() => {
    console.log("Heatmap visibility changed:", isHeatmapVisible);
    if (isHeatmapVisible) {
      applyHeatmapMaterial();
      //applyHeatmapColors(group.current);
    } else {
      restoreOriginalMaterial();
    }
  }, [isHeatmapVisible, heatmapMaterial, originalMaterials]);

  // useFrame(() => {
  //   group.current.rotation.y += rotationSpeed; // Rotate the model around its y-axis
  // });

  useFrame(() => {
    group.current.rotation.x = -Math.PI / 2.4;
    group.current.rotation.y = -Math.PI / 2; // Rotate by -90 degrees around the X-axis
    group.current.rotation.z = -0.05;
  });

  // Calculate heatmap colors based on vertex Y values
  // const calculateHeatmapColor = (z) => {
  //   const normalizedY = (z + 1) / 2; // Normalize Y value between 0 and 1
  //   const r = 1 - normalizedY; // Red component decreases as Y value increases
  //   const g = z; // Green component increases as Y value increases
  //   const b = 0; // Blue component remains constant
  //   return new THREE.Color(r, g, b);
  // };

  // const applyHeatmapColors = () => {
  //   Object.values(nodes).forEach((node) => {
  //     if (node.isMesh) {
  //       const vertices = node.geometry.attributes.position;
  //       const colors = [];
  //       heatmapMaterial.name = node.material.name;
  //       for (let i = 0; i < vertices.count; i++) {
  //         const y = vertices.getY(i);
  //         const color = calculateHeatmapColor(y);
  //         //colors.push(color.r, color.g, color.b);
  //         heatmapMaterial.color = color.r;
  //       }
  //       node.material = heatmapMaterial.clone();
  //       // node.geometry.setAttribute(
  //       //   "color",
  //       //   new THREE.BufferAttribute(new Float32Array(colors), 3)
  //       // );
  //     }
  //   });
  //   setHeatMapVisible(true);
  // };

  const applyHeatmapMaterial = () => {
    // Apply heatmap material to each mesh
    Object.values(nodes).forEach((node) => {
      if (node.isMesh) {
        heatmapMaterial.name = node.material.name;
        if (node.material.name.startsWith("BuildingMat-000")) {
          heatmapMaterial.color.setHex(0xff0000);
        } else if (node.material.name.startsWith("BuildingMat-001")) {
          heatmapMaterial.color.setHex(0xffff00);
        } else if (node.material.name.startsWith("BuildingMat-002")) {
          heatmapMaterial.color.setHex(0x00ff00);
        }
        node.material = heatmapMaterial.clone();
      }
    });
    console.log("+++++++++++++++++++++++++++++++++++");
    Object.values(nodes).forEach((node) => {
      if (node.isMesh) {
        console.log(node.material);
      }
    });
    console.log("+++++++++++++++++++++++++++++++++++");
    setHeatMapVisible(true);
  };

  const restoreOriginalMaterial = () => {
    // Restore original material to each mesh
    console.log("----------------------------------------------------------");
    Object.values(nodes).forEach((node) => {
      if (node.isMesh) {
        const originalMaterial = originalMaterials[node.material.name];
        if (originalMaterial) {
          node.material = originalMaterial;
          console.log(node.material); // Make sure to clone the original material before assigning
        }
      }
    });
    setHeatMapVisible(false);
    console.log("========================================================");
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.5}>
        {Object.keys(nodes).map((nodeName) => {
          const node = nodes[nodeName];
          if (node.isMesh) {
            return (
              <mesh
                key={nodeName}
                geometry={node.geometry}
                material={node.material}
              />
            );
          }
          return null;
        })}
      </group>
    </group>
  );
}
