// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.16 scene.gltf
// Author: Twin Dragon Studios (https://sketchfab.com/RHALL)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/ocean-wave-wmaya-03f0559f6b7646ea9014e2e72f71b198
// Title: Ocean Wave -  w/Maya
// */

// import React, { useRef } from "react";
// import { useGLTF, useAnimations } from "@react-three/drei";

// export function Ocean(props) {
//   const group = useRef();
//   const { nodes, materials, animations } = useGLTF("/ocean.gltf");
//   const { actions } = useAnimations(animations, group);
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Sketchfab_Scene">
//         <group name="Sketchfab_model">
//           <group name="sketchfabtimeframe">
//             <group name="Object_2" scale={0}>
//               <group name="frame_97">
//                 <mesh
//                   name="Object_4"
//                   geometry={nodes.Object_4.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_5" scale={0}>
//               <group name="frame_96">
//                 <mesh
//                   name="Object_7"
//                   geometry={nodes.Object_7.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_8" scale={0}>
//               <group name="frame_95">
//                 <mesh
//                   name="Object_10"
//                   geometry={nodes.Object_10.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_11" scale={0}>
//               <group name="frame_94">
//                 <mesh
//                   name="Object_13"
//                   geometry={nodes.Object_13.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_14" scale={0}>
//               <group name="frame_93">
//                 <mesh
//                   name="Object_16"
//                   geometry={nodes.Object_16.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_17" scale={0}>
//               <group name="frame_92">
//                 <mesh
//                   name="Object_19"
//                   geometry={nodes.Object_19.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_20" scale={0}>
//               <group name="frame_91">
//                 <mesh
//                   name="Object_22"
//                   geometry={nodes.Object_22.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_23" scale={0}>
//               <group name="frame_90">
//                 <mesh
//                   name="Object_25"
//                   geometry={nodes.Object_25.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_26" scale={0}>
//               <group name="frame_89">
//                 <mesh
//                   name="Object_28"
//                   geometry={nodes.Object_28.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_29" scale={0}>
//               <group name="frame_88">
//                 <mesh
//                   name="Object_31"
//                   geometry={nodes.Object_31.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_32" scale={0}>
//               <group name="frame_87">
//                 <mesh
//                   name="Object_34"
//                   geometry={nodes.Object_34.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_35" scale={0}>
//               <group name="frame_86">
//                 <mesh
//                   name="Object_37"
//                   geometry={nodes.Object_37.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_38" scale={0}>
//               <group name="frame_85">
//                 <mesh
//                   name="Object_40"
//                   geometry={nodes.Object_40.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_41" scale={0}>
//               <group name="frame_84">
//                 <mesh
//                   name="Object_43"
//                   geometry={nodes.Object_43.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_44" scale={0}>
//               <group name="frame_83">
//                 <mesh
//                   name="Object_46"
//                   geometry={nodes.Object_46.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_47" scale={0}>
//               <group name="frame_82">
//                 <mesh
//                   name="Object_49"
//                   geometry={nodes.Object_49.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_50" scale={0}>
//               <group name="frame_81">
//                 <mesh
//                   name="Object_52"
//                   geometry={nodes.Object_52.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_53" scale={0}>
//               <group name="frame_80">
//                 <mesh
//                   name="Object_55"
//                   geometry={nodes.Object_55.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_56" scale={0}>
//               <group name="frame_79">
//                 <mesh
//                   name="Object_58"
//                   geometry={nodes.Object_58.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_59" scale={0}>
//               <group name="frame_78">
//                 <mesh
//                   name="Object_61"
//                   geometry={nodes.Object_61.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_62" scale={0}>
//               <group name="frame_77">
//                 <mesh
//                   name="Object_64"
//                   geometry={nodes.Object_64.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_65" scale={0}>
//               <group name="frame_76">
//                 <mesh
//                   name="Object_67"
//                   geometry={nodes.Object_67.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_68" scale={0}>
//               <group name="frame_75">
//                 <mesh
//                   name="Object_70"
//                   geometry={nodes.Object_70.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_71" scale={0}>
//               <group name="frame_74">
//                 <mesh
//                   name="Object_73"
//                   geometry={nodes.Object_73.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_74" scale={0}>
//               <group name="frame_73">
//                 <mesh
//                   name="Object_76"
//                   geometry={nodes.Object_76.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_77" scale={0}>
//               <group name="frame_72">
//                 <mesh
//                   name="Object_79"
//                   geometry={nodes.Object_79.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_80" scale={0}>
//               <group name="frame_71">
//                 <mesh
//                   name="Object_82"
//                   geometry={nodes.Object_82.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_83" scale={0}>
//               <group name="frame_70">
//                 <mesh
//                   name="Object_85"
//                   geometry={nodes.Object_85.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_86" scale={0}>
//               <group name="frame_69">
//                 <mesh
//                   name="Object_88"
//                   geometry={nodes.Object_88.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_89" scale={0}>
//               <group name="frame_68">
//                 <mesh
//                   name="Object_91"
//                   geometry={nodes.Object_91.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_92" scale={0}>
//               <group name="frame_67">
//                 <mesh
//                   name="Object_94"
//                   geometry={nodes.Object_94.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_95" scale={0}>
//               <group name="frame_66">
//                 <mesh
//                   name="Object_97"
//                   geometry={nodes.Object_97.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_98" scale={0}>
//               <group name="frame_65">
//                 <mesh
//                   name="Object_100"
//                   geometry={nodes.Object_100.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_101" scale={0}>
//               <group name="frame_64">
//                 <mesh
//                   name="Object_103"
//                   geometry={nodes.Object_103.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_104" scale={0}>
//               <group name="frame_63">
//                 <mesh
//                   name="Object_106"
//                   geometry={nodes.Object_106.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_107" scale={0}>
//               <group name="frame_62">
//                 <mesh
//                   name="Object_109"
//                   geometry={nodes.Object_109.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_110" scale={0}>
//               <group name="frame_61">
//                 <mesh
//                   name="Object_112"
//                   geometry={nodes.Object_112.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_113" scale={0}>
//               <group name="frame_60">
//                 <mesh
//                   name="Object_115"
//                   geometry={nodes.Object_115.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_116" scale={0}>
//               <group name="frame_59">
//                 <mesh
//                   name="Object_118"
//                   geometry={nodes.Object_118.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_119" scale={0}>
//               <group name="frame_58">
//                 <mesh
//                   name="Object_121"
//                   geometry={nodes.Object_121.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_122" scale={0}>
//               <group name="frame_57">
//                 <mesh
//                   name="Object_124"
//                   geometry={nodes.Object_124.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_125" scale={0}>
//               <group name="frame_56">
//                 <mesh
//                   name="Object_127"
//                   geometry={nodes.Object_127.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_128" scale={0}>
//               <group name="frame_55">
//                 <mesh
//                   name="Object_130"
//                   geometry={nodes.Object_130.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_131" scale={0}>
//               <group name="frame_54">
//                 <mesh
//                   name="Object_133"
//                   geometry={nodes.Object_133.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_134" scale={0}>
//               <group name="frame_53">
//                 <mesh
//                   name="Object_136"
//                   geometry={nodes.Object_136.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_137" scale={0}>
//               <group name="frame_52">
//                 <mesh
//                   name="Object_139"
//                   geometry={nodes.Object_139.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_140" scale={0}>
//               <group name="frame_51">
//                 <mesh
//                   name="Object_142"
//                   geometry={nodes.Object_142.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_143" scale={0}>
//               <group name="frame_50">
//                 <mesh
//                   name="Object_145"
//                   geometry={nodes.Object_145.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_146" scale={0}>
//               <group name="frame_49">
//                 <mesh
//                   name="Object_148"
//                   geometry={nodes.Object_148.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_149" scale={0}>
//               <group name="frame_48">
//                 <mesh
//                   name="Object_151"
//                   geometry={nodes.Object_151.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_152" scale={0}>
//               <group name="frame_47">
//                 <mesh
//                   name="Object_154"
//                   geometry={nodes.Object_154.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_155" scale={0}>
//               <group name="frame_46">
//                 <mesh
//                   name="Object_157"
//                   geometry={nodes.Object_157.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_158" scale={0}>
//               <group name="frame_45">
//                 <mesh
//                   name="Object_160"
//                   geometry={nodes.Object_160.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_161" scale={0}>
//               <group name="frame_44">
//                 <mesh
//                   name="Object_163"
//                   geometry={nodes.Object_163.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_164" scale={0}>
//               <group name="frame_43">
//                 <mesh
//                   name="Object_166"
//                   geometry={nodes.Object_166.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_167" scale={0}>
//               <group name="frame_42">
//                 <mesh
//                   name="Object_169"
//                   geometry={nodes.Object_169.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_170" scale={0}>
//               <group name="frame_41">
//                 <mesh
//                   name="Object_172"
//                   geometry={nodes.Object_172.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_173" scale={0}>
//               <group name="frame_40">
//                 <mesh
//                   name="Object_175"
//                   geometry={nodes.Object_175.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_176" scale={0}>
//               <group name="frame_39">
//                 <mesh
//                   name="Object_178"
//                   geometry={nodes.Object_178.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_179" scale={0}>
//               <group name="frame_38">
//                 <mesh
//                   name="Object_181"
//                   geometry={nodes.Object_181.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_182" scale={0}>
//               <group name="frame_37">
//                 <mesh
//                   name="Object_184"
//                   geometry={nodes.Object_184.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_185" scale={0}>
//               <group name="frame_36">
//                 <mesh
//                   name="Object_187"
//                   geometry={nodes.Object_187.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_188" scale={0}>
//               <group name="frame_35">
//                 <mesh
//                   name="Object_190"
//                   geometry={nodes.Object_190.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_191" scale={0}>
//               <group name="frame_34">
//                 <mesh
//                   name="Object_193"
//                   geometry={nodes.Object_193.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_194" scale={0}>
//               <group name="frame_33">
//                 <mesh
//                   name="Object_196"
//                   geometry={nodes.Object_196.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_197" scale={0}>
//               <group name="frame_32">
//                 <mesh
//                   name="Object_199"
//                   geometry={nodes.Object_199.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_200" scale={0}>
//               <group name="frame_31">
//                 <mesh
//                   name="Object_202"
//                   geometry={nodes.Object_202.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_203" scale={0}>
//               <group name="frame_30">
//                 <mesh
//                   name="Object_205"
//                   geometry={nodes.Object_205.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_206" scale={0}>
//               <group name="frame_29">
//                 <mesh
//                   name="Object_208"
//                   geometry={nodes.Object_208.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_209" scale={0}>
//               <group name="frame_28">
//                 <mesh
//                   name="Object_211"
//                   geometry={nodes.Object_211.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_212" scale={0}>
//               <group name="frame_27">
//                 <mesh
//                   name="Object_214"
//                   geometry={nodes.Object_214.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_215" scale={0}>
//               <group name="frame_26">
//                 <mesh
//                   name="Object_217"
//                   geometry={nodes.Object_217.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_218" scale={0}>
//               <group name="frame_25">
//                 <mesh
//                   name="Object_220"
//                   geometry={nodes.Object_220.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_221" scale={0}>
//               <group name="frame_24">
//                 <mesh
//                   name="Object_223"
//                   geometry={nodes.Object_223.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_224" scale={0}>
//               <group name="frame_23">
//                 <mesh
//                   name="Object_226"
//                   geometry={nodes.Object_226.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_227" scale={0}>
//               <group name="frame_22">
//                 <mesh
//                   name="Object_229"
//                   geometry={nodes.Object_229.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_230" scale={0}>
//               <group name="frame_21">
//                 <mesh
//                   name="Object_232"
//                   geometry={nodes.Object_232.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_233" scale={0}>
//               <group name="frame_20">
//                 <mesh
//                   name="Object_235"
//                   geometry={nodes.Object_235.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_236" scale={0}>
//               <group name="frame_19">
//                 <mesh
//                   name="Object_238"
//                   geometry={nodes.Object_238.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_239" scale={0}>
//               <group name="frame_18">
//                 <mesh
//                   name="Object_241"
//                   geometry={nodes.Object_241.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_242" scale={0}>
//               <group name="frame_17">
//                 <mesh
//                   name="Object_244"
//                   geometry={nodes.Object_244.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_245" scale={0}>
//               <group name="frame_16">
//                 <mesh
//                   name="Object_247"
//                   geometry={nodes.Object_247.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_248" scale={0}>
//               <group name="frame_15">
//                 <mesh
//                   name="Object_250"
//                   geometry={nodes.Object_250.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_251" scale={0}>
//               <group name="frame_14">
//                 <mesh
//                   name="Object_253"
//                   geometry={nodes.Object_253.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_254" scale={0}>
//               <group name="frame_13">
//                 <mesh
//                   name="Object_256"
//                   geometry={nodes.Object_256.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_257" scale={0}>
//               <group name="frame_12">
//                 <mesh
//                   name="Object_259"
//                   geometry={nodes.Object_259.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_260" scale={0}>
//               <group name="frame_11">
//                 <mesh
//                   name="Object_262"
//                   geometry={nodes.Object_262.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_263" scale={0}>
//               <group name="frame_10">
//                 <mesh
//                   name="Object_265"
//                   geometry={nodes.Object_265.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_266" scale={0}>
//               <group name="frame_9">
//                 <mesh
//                   name="Object_268"
//                   geometry={nodes.Object_268.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_269" scale={0}>
//               <group name="frame_8">
//                 <mesh
//                   name="Object_271"
//                   geometry={nodes.Object_271.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_272" scale={0}>
//               <group name="frame_7">
//                 <mesh
//                   name="Object_274"
//                   geometry={nodes.Object_274.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_275" scale={0}>
//               <group name="frame_6">
//                 <mesh
//                   name="Object_277"
//                   geometry={nodes.Object_277.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_278" scale={0}>
//               <group name="frame_5">
//                 <mesh
//                   name="Object_280"
//                   geometry={nodes.Object_280.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_281" scale={0}>
//               <group name="frame_4">
//                 <mesh
//                   name="Object_283"
//                   geometry={nodes.Object_283.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_284" scale={0}>
//               <group name="frame_3">
//                 <mesh
//                   name="Object_286"
//                   geometry={nodes.Object_286.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_287" scale={0}>
//               <group name="frame_2">
//                 <mesh
//                   name="Object_289"
//                   geometry={nodes.Object_289.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_290" scale={0}>
//               <group name="frame_1">
//                 <mesh
//                   name="Object_292"
//                   geometry={nodes.Object_292.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//             <group name="Object_293">
//               <group name="frame_0">
//                 <mesh
//                   name="Object_295"
//                   geometry={nodes.Object_295.geometry}
//                   material={materials.blinn1SG}
//                 />
//               </group>
//             </group>
//           </group>
//         </group>
//       </group>
//       <group>
//         {Object.keys(nodes).map((nodeName) => {
//           const node = nodes[nodeName];
//           if (node.isMesh) {
//             return (
//               <mesh
//                 key={nodeName}
//                 geometry={node.geometry}
//                 material={node.material}
//               />
//             );
//           }
//           return null;
//         })}
//       </group>
//     </group>
//   );
//   console.log("Done");
// }

// useGLTF.preload("/ocean.gltf");

// import React, { useEffect } from "react";
// import * as THREE from "three";
// import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
// import { Water } from "three/examples/jsm/objects/Water.js";
// import { Sky } from "three/examples/jsm/objects/Sky.js";
// import Stats from "three/examples/jsm/libs/stats.module.js";
// //import { GUI } from "three/examples/jsm/libs/dat.gui.module.js";
// import { GUI } from "three/examples/jsm/libs/lil-gui.module.min.js";
// //import { GUI } from "dat.gui";

// function ThreeJsComponent() {
//   useEffect(() => {
//     let container, stats;
//     let camera, scene, renderer;
//     let controls, water, sun, mesh;

//     init();
//     animate();

//     function init() {
//       container = document.getElementById("container");

//       renderer = new THREE.WebGLRenderer();
//       renderer.setPixelRatio(window.devicePixelRatio);
//       renderer.setSize(window.innerWidth, window.innerHeight);
//       renderer.toneMapping = THREE.ACESFilmicToneMapping;
//       renderer.toneMappingExposure = 0.5;
//       container.appendChild(renderer.domElement);

//       scene = new THREE.Scene();

//       camera = new THREE.PerspectiveCamera(
//         55,
//         window.innerWidth / window.innerHeight,
//         1,
//         20000
//       );
//       camera.position.set(30, 30, 100);

//       sun = new THREE.Vector3();

//       const waterGeometry = new THREE.PlaneGeometry(10000, 10000);

//       water = new Water(waterGeometry, {
//         textureWidth: 512,
//         textureHeight: 512,
//         waterNormals: new THREE.TextureLoader().load(
//           "textures/waternormals.jpg",
//           function (texture) {
//             texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
//           }
//         ),
//         sunDirection: new THREE.Vector3(),
//         sunColor: 0xffffff,
//         waterColor: 0x001e0f,
//         distortionScale: 3.7,
//         fog: scene.fog !== undefined,
//       });

//       water.rotation.x = -Math.PI / 2;

//       scene.add(water);

//       const sky = new Sky();
//       sky.scale.setScalar(10000);
//       scene.add(sky);

//       const skyUniforms = sky.material.uniforms;

//       skyUniforms["turbidity"].value = 10;
//       skyUniforms["rayleigh"].value = 2;
//       skyUniforms["mieCoefficient"].value = 0.005;
//       skyUniforms["mieDirectionalG"].value = 0.8;

//       const parameters = {
//         elevation: 2,
//         azimuth: 180,
//       };

//       const pmremGenerator = new THREE.PMREMGenerator(renderer);
//       const sceneEnv = new THREE.Scene();

//       let renderTarget;

//       function updateSun() {
//         const phi = THREE.MathUtils.degToRad(90 - parameters.elevation);
//         const theta = THREE.MathUtils.degToRad(parameters.azimuth);

//         sun.setFromSphericalCoords(1, phi, theta);

//         sky.material.uniforms["sunPosition"].value.copy(sun);
//         water.material.uniforms["sunDirection"].value.copy(sun).normalize();

//         if (renderTarget !== undefined) renderTarget.dispose();

//         sceneEnv.add(sky);
//         renderTarget = pmremGenerator.fromScene(sceneEnv);
//         scene.add(sky);

//         scene.environment = renderTarget.texture;
//       }

//       updateSun();

//       const geometry = new THREE.BoxGeometry(30, 30, 30);
//       const material = new THREE.MeshStandardMaterial({ roughness: 0 });

//       // mesh = new THREE.Mesh(geometry, material);
//       // scene.add(mesh);

//       controls = new OrbitControls(camera, renderer.domElement);
//       controls.maxPolarAngle = Math.PI * 0.495;
//       controls.target.set(0, 10, 0);
//       controls.minDistance = 40.0;
//       controls.maxDistance = 200.0;
//       controls.update();

//       stats = new Stats();
//       container.appendChild(stats.dom);

//       const gui = new GUI();

//       const folderSky = gui.addFolder("Sky");
//       folderSky.add(parameters, "elevation", 0, 90, 0.1).onChange(updateSun);
//       folderSky.add(parameters, "azimuth", -180, 180, 0.1).onChange(updateSun);
//       folderSky.open();

//       const waterUniforms = water.material.uniforms;

//       const folderWater = gui.addFolder("Water");
//       folderWater
//         .add(waterUniforms.distortionScale, "value", 0, 8, 0.1)
//         .name("distortionScale");
//       folderWater.add(waterUniforms.size, "value", 0.1, 10, 0.1).name("size");
//       folderWater.open();

//       window.addEventListener("resize", onWindowResize);
//     }

//     function onWindowResize() {
//       camera.aspect = window.innerWidth / window.innerHeight;
//       camera.updateProjectionMatrix();
//       renderer.setSize(window.innerWidth, window.innerHeight);
//     }

//     function animate() {
//       requestAnimationFrame(animate);
//       render();
//       stats.update();
//     }

//     function render() {
//       const time = performance.now() * 0.001;

//       // mesh.position.y = Math.sin(time) * 20 + 5;
//       // mesh.rotation.x = time * 0.5;
//       // mesh.rotation.z = time * 0.51;

//       water.material.uniforms["time"].value += 1.0 / 60.0;

//       renderer.render(scene, camera);
//     }
//   }, []); // Empty dependency array to run once on mount

//   return <div id="container"></div>;
// }

// export default ThreeJsComponent;

import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { Water } from "three/examples/jsm/objects/Water.js";
import { Sky } from "three/examples/jsm/objects/Sky.js";
import Stats from "three/examples/jsm/libs/stats.module.js";
import { GUI } from "three/examples/jsm/libs/lil-gui.module.min.js";
// import { GUI } from "dat.gui";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";
//import AudioPlayer from "./AudioPlayer";

function ThreeJsComponent() {
  const audioRef = useRef(null);
  const isRendered = useRef(false);
  useEffect(() => {
    let container, stats;
    let camera, scene, renderer;
    let controls,
      water,
      sun,
      mesh,
      heatmapMesh,
      tokyoModel,
      tokyoModelHeatMap,
      cityModel,
      cityModelHeatMap;
    let heatmapVisible = false;
    let cityModelVisible = false;

    init();
    //animate();

    function init() {
      if (!isRendered.current) {
        isRendered.current = true;
        container = document.getElementById("container");

        renderer = new THREE.WebGLRenderer();
        renderer.setPixelRatio(window.devicePixelRatio);
        renderer.setSize(window.innerWidth, window.innerHeight);
        renderer.toneMapping = THREE.ACESFilmicToneMapping;
        renderer.toneMappingExposure = 0.5;
        container.appendChild(renderer.domElement);

        scene = new THREE.Scene();

        camera = new THREE.PerspectiveCamera(
          55,
          window.innerWidth / window.innerHeight,
          1,
          20000
        );
        camera.position.set(30, 30, 100);

        sun = new THREE.Vector3();

        const waterGeometry = new THREE.PlaneGeometry(10000, 10000);

        water = new Water(waterGeometry, {
          textureWidth: 512,
          textureHeight: 512,
          waterNormals: new THREE.TextureLoader().load(
            "textures/waternormals.jpg",
            function (texture) {
              texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
            }
          ),
          sunDirection: new THREE.Vector3(),
          sunColor: 0xffffff,
          waterColor: 0x001e0f,
          distortionScale: 3.7,
          fog: scene.fog !== undefined,
        });

        water.rotation.x = -Math.PI / 2;

        scene.add(water);

        const sky = new Sky();
        sky.scale.setScalar(10000);
        scene.add(sky);

        const skyUniforms = sky.material.uniforms;

        skyUniforms["turbidity"].value = 10;
        skyUniforms["rayleigh"].value = 2;
        skyUniforms["mieCoefficient"].value = 0.005;
        skyUniforms["mieDirectionalG"].value = 0.8;

        const parameters = {
          elevation: 2,
          azimuth: 180,
          waterLevel: 5, // Initial water level
        };

        const pmremGenerator = new THREE.PMREMGenerator(renderer);
        const sceneEnv = new THREE.Scene();

        let renderTarget;

        function updateSun() {
          const phi = THREE.MathUtils.degToRad(90 - parameters.elevation);
          const theta = THREE.MathUtils.degToRad(parameters.azimuth);

          sun.setFromSphericalCoords(1, phi, theta);

          sky.material.uniforms["sunPosition"].value.copy(sun);
          water.material.uniforms["sunDirection"].value.copy(sun).normalize();

          if (renderTarget !== undefined) renderTarget.dispose();

          sceneEnv.add(sky);
          renderTarget = pmremGenerator.fromScene(sceneEnv);
          scene.add(sky);

          scene.environment = renderTarget.texture;
        }

        updateSun();

        const geometry = new THREE.BoxGeometry(30, 30, 30);
        const material = new THREE.MeshStandardMaterial({ roughness: 0 });

        const dracoLoader = new DRACOLoader();
        dracoLoader.setDecoderPath("jsm/libs/draco/gltf/");

        const loader = new GLTFLoader();
        loader.setDRACOLoader(dracoLoader);
        loader.load(
          "models/gltf/LittlestTokyo.glb",
          function (gltf) {
            tokyoModel = gltf.scene;
            tokyoModel.position.set(1, 24, 0);
            tokyoModel.scale.set(0.12, 0.12, 0.12);
            scene.add(tokyoModel);
            tokyoModelHeatMap = tokyoModel.clone();

            // Traverse through model's children and set heatmap texture to materials
            tokyoModelHeatMap.traverse((child) => {
              if (child instanceof THREE.Mesh) {
                child.material = new THREE.MeshBasicMaterial({
                  map: createHeatmapTexture(),
                  transparent: true,
                  opacity: 1, // Set opacity based on heatmap visibility
                });
              }
            });

            animate();
          },
          undefined,
          function (e) {
            console.error(e);
          }
        );

        loader.load(
          "/city.glb",
          function (gltf) {
            cityModel = gltf.scene;
            cityModel.position.set(-35, 5, -40);
            cityModel.scale.set(4.5, 4.5, 4.5);
            //scene.add(cityModel);
            cityModelHeatMap = cityModel.clone();

            // Traverse through model's children and set heatmap texture to materials
            cityModelHeatMap.traverse((child) => {
              if (child instanceof THREE.Mesh) {
                child.material = new THREE.MeshBasicMaterial({
                  map: createHeatmapTexture(),
                  transparent: true,
                  opacity: 1, // Set opacity based on heatmap visibility
                });
              }
            });

            animate();
          },
          undefined,
          function (e) {
            console.error(e);
          }
        );

        controls = new OrbitControls(camera, renderer.domElement);
        controls.maxPolarAngle = Math.PI * 0.495;
        controls.target.set(0, 10, 0);
        controls.minDistance = 40.0;
        controls.maxDistance = 200.0;
        controls.update();

        stats = new Stats();
        container.appendChild(stats.dom);

        const gui = new GUI();

        const folderSky = gui.addFolder("Sky");
        folderSky.add(parameters, "elevation", 0, 90, 0.1).onChange(updateSun);
        folderSky
          .add(parameters, "azimuth", -180, 180, 0.1)
          .onChange(updateSun);
        folderSky.open();

        const waterUniforms = water.material.uniforms;

        const folderWater = gui.addFolder("Water");
        folderWater
          .add(waterUniforms.distortionScale, "value", 0, 8, 0.1)
          .name("distortionScale");
        folderWater.add(waterUniforms.size, "value", 0.1, 10, 0.1).name("size");

        // Add a slider for adjusting water level
        folderWater.add(parameters, "waterLevel", 0, 15, 0.1).onChange(() => {
          water.position.y = parameters.waterLevel;
        });

        folderWater.open();

        const folderHeatmap = gui.addFolder("Heatmap");
        folderHeatmap
          .add({ visible: heatmapVisible }, "visible") // Add checkbox to toggle heatmap visibility
          .onChange((value) => {
            heatmapVisible = value;
            if (heatmapVisible) {
              if (cityModelVisible) {
                scene.remove(cityModel);
                scene.add(cityModelHeatMap);
              } else {
                scene.remove(tokyoModel);
                scene.add(tokyoModelHeatMap);
              }
            } else {
              if (cityModelVisible) {
                scene.remove(cityModelHeatMap);
                scene.add(cityModel);
              } else {
                scene.remove(tokyoModelHeatMap);
                scene.add(tokyoModel);
              }
            }
          });
        folderHeatmap.open();

        const folderCityModel = gui.addFolder("City");
        folderCityModel
          .add({ visible: cityModelVisible }, "visible") // Add checkbox to toggle heatmap visibility
          .onChange((value) => {
            cityModelVisible = value;
            if (cityModelVisible) {
              if (heatmapVisible) {
                scene.remove(tokyoModelHeatMap);
                scene.add(cityModelHeatMap);
              } else {
                scene.remove(tokyoModel);
                scene.add(cityModel);
              }
            } else {
              if (heatmapVisible) {
                scene.remove(cityModelHeatMap);
                scene.add(tokyoModelHeatMap);
              } else {
                scene.remove(cityModel);
                scene.add(tokyoModel);
              }
            }
          });
        folderCityModel.open();

        window.addEventListener("resize", onWindowResize);
      }

      function onWindowResize() {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(window.innerWidth, window.innerHeight);
      }

      function animate() {
        requestAnimationFrame(animate);
        render();
        stats.update();
      }

      function render() {
        const time = performance.now() * 0.001;

        // mesh.position.y = Math.sin(time) * 20 + 5;
        // mesh.rotation.x = time * 0.5;
        // mesh.rotation.z = time * 0.51;

        water.material.uniforms["time"].value += 1.0 / 60.0;

        renderer.render(scene, camera);
      }

      // Function to create a heatmap texture
      function createHeatmapTexture() {
        const canvas = document.createElement("canvas");
        canvas.width = 1;
        canvas.height = 256;
        const ctx = canvas.getContext("2d");

        // Define colors
        const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height);
        gradient.addColorStop(0, "red"); // Base color (bottom)
        gradient.addColorStop(0.25, "yellow"); // Transition to yellow
        gradient.addColorStop(0.5, "green"); // Transition to green
        gradient.addColorStop(0.75, "blue"); // Transition to blue
        gradient.addColorStop(1, "blue"); // Top color

        // Fill gradient
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, 1, 256);

        const texture = new THREE.CanvasTexture(canvas);
        return texture;
      }
    }
  }, []); // Empty dependency array to run once on mount

  return <div id="container"></div>;
}

export default ThreeJsComponent;
